### ISSUE TITLE
Module not found: Error: Can't resolve './components/MainContent' 

### ISSUE THREAD

**Issue by jose2007kj** [vitormalencar/vitormalencar_pwa#2]
`ERROR in ./src/index.js
Module not found: Error: Can't resolve './components/MainContent' in '/media/mary/7703C004/kj_projects/16.04/kj/preact/test/vitormalencar_pwa/src'
 @ ./src/index.js 1:214-264
`
first of all thanks for this opensource project.
sir,
i am getting the above error when doing yarn build ...........where i migh be going wrong

**Comment by vitormalencar** [comment]
hey man so sorry to leve you in the dark busy days,
can you tell me the steps to reproduce  the error ?

**Comment by jose2007kj** [comment]
no issues sir,thanks sir........... i got the error while doing `npm run build`

**Comment by vitormalencar** [comment]
I could not reproduce the error, following the README I downloaded the repository
I installed the dependencies
`npm i`
I've created the optimized build file
`npm run build`

and everything seems to be working normally,

you could delete your node_modules folder and try to install the dependencies again to see if anything was wrong with the installation

**Comment by jose2007kj** [comment]
ok  sir thanks... i will check that........

**Comment by jose2007kj** [comment]
i think some issue with my system..... thanks sir
